var zodiac = [
	{
		sign: "aquarius",		
		personality: "Strengths include: being witty, clever, inventive and original.   Weakness: stubborn, unemotional, sarcastic, rebellious, aloof",
		temperament: "Aquarius is the sign of visionaries, unconventionality and intellectual independence. Aquarius are the people who deviate from the crowd and go their own way. They are always after intellectual stimulation, constantly discovering something new, forming new opinions and stubbornly traveling their way regardless of what other people think. Aquarius are filled with paradoxes, they are interested in the opposite ends of the spectrum, they like to be alone yet are social butterflies, they like to experience both sides and see both opinions as they formulate new ideas with their forward thinking, active mind. Aquarius have a 'live and let live' policy where everyone is free to be themselves, an Aquarius never judges others because as human beings, we are all equal and entitled to our own opinions. They are verbally skilled and very witty, they observe people and learn how to interact with others through observation. They can be masters of manipulation justifying anything they do or think. As a result, they can deal with any type of personality and adapt to any situation. They welcome change because boredom is their enemy. Anything new is an opportunity to Aquarius. Aquarius can act as an expert on any topic, they are very good at inflating their own importance, they feel it is deserved because their eccentricity makes them unique. Conventional people beware, Aquarius likes to shock and deviate from the norm, this is how they live. Aquarius is known to pick at anyone they find weak or dull-minded. It is simply an easy target for verbal exercise for them, no harm is meant but it might be taken from the other person. Deep inside, Aquarius would never intentionally hurt anyone, they have respect for every human, even thought this might not seem apparent to the more emotional types.",
		img: "img/aquarius.png"
	},
	{
		sign: "pisces",		
		personality: "Strenths: compassionate, adaptable, accepting,devoted and imaginative.   Weaknesses: Oversensitive, indecisive, self-pitying, lazy, escapist",
		temperament: "Pisces is the sign of mysticism, mystery and the spiritual unknown. Pisces live in two worlds, the real world and the spiritual or mystical world where they interpret what they see into what they want. They do this to avoid all the realities of pain and suffering in the world. They have extremes of emotions and feel both good and bad intensively. Pisces have formidable intuitive ability. Most Pisces are somehow involved with occult or spiritualism. Pisces are very good at understanding people for they have the ability to delve into the psyche and see behind a person's motivations. Pisces are prone to drug addiction and indulging lifestyles because of their eternal search for themselves and their fear of confrontation and having to change a situation, also they justify drug use by allowing it to get closer with their 'spiritual selves'. Once they aware this is why they are doing it, it will be easier to kick the habit. Pisces are not the pushovers that they may seem, in fact they have strength of character and will stand up for what they believe in and and they can do hard work for something they believe in. They can be very lazy but only in matters that they do not care about. Pisces is the most sensitive of all zodiac signs.",
		img: "img/pisces.jpg"
	},
	{
		sign: "aries",		
		personality: "Strengths: Independant, generous, optimistic, enthusiastic, courageous.   Weaknesses: moody, short tempered, self-involved, impulsive, inpatient",
		temperament: "Aries is the first of the zodiac signs. Aries is the sign of the self, people born under this sign strongly project their personalities onto others and can be very self-oriented. Aries tend to venture out into the world and leave impressions on others that they are exciting, vibrant and talkative. Aries tend to live adventurous lives and like to be the center of attention, but rightly so since they are natural, confident leaders. Aries are enthusiastic about their goals and enjoy the thrill of the hunt, wanting is always better then getting is a good way to sum it up. Aries are very impulsive and usually do not think before they act - or speak. Too often Aries will say whatever pops into their head and usually end up regretting it later! ",
		img: "img/aries.jpg"
	},
	{
		sign: "cancer",		
		personality: "Strengths: loyal, dependable, caring, adaptable, responsive.   Weaknesses: moody, clingy, self-pitying, Oversensitive, self-absorbed",
		temperament: "Cancer is a mysterious sign, filled with contradictions. They want security and comfort yet seek new adventure. They are very helpful to others yet sometimes can be cranky and indifferent. Cancer has a driving, forceful personality that can be easily hidden beneath a calm, and cool exterior. The crab is Cancer's ruling animal and it suits them well, they can come out of their shell and fight but they can also hide in their shell of skitter away back into the depths of the ocean. They are very unpredictable. With cancer, there is always something more that meets the eye, for they are always partially hidden behind the shell. They are a have a deep psyche and intuitive mind that is hidden from the world. Cancer is deeply sensitive and easily hurt, this might be why they have their defense shell in place, to avoids being hurt by others. They are nurturers so they surround themselves with people, whom after a while can offend or hurt a cancer without even knowing they did so, therefore Cancer's protective shell keeps them safe from hurt. They are complex, fragile, unpredictable and temperamental and need constant support and encouragement, more then any other astrology signs, Cancer needs to be needed. When cancer gets the support it needs, it has a tremendous amount to offer in return. When cancer gets offended, they tend to sulk instead of confronting the persons face to face. This needlessly prolongs the pain and suffering. Cancer is very possessive, not just with material possessions but with people as well. Cancer will always want to stay in touch with old friends and anyone who has ever been close to them, because it is easier to maintain a friendship then attempt to learn to trust a new person. It is easier this way for them emotionally. If you befriend a Cancer, you will stay friends for a long time. Cancer makes the perfect mother, this is the sign that represents motherhood. They have unconditional love and caring more so then any other astrology sign. Cancer are very intuitive. Most of the psychics of the world are Cancer astrology signs. They have an excellent memory and are very observant and can read people very well. They can usually tell of other people's intentions are good or not. Never dupe a Cancer, they can see your motives. Cancer has a lot of emotional issues to deal with but once they overcome this large hump of shyness and insecurity, there is practically nothing they can't do. With their strong intuition, sensitivity, powers of observation and intelligence, they will have great success in anything they undertake. ",
		img: "img/cancer.jpg"
	},
	{
		sign: "capricor",		
		personality: "Strengths: responsible, patient, amitious, resourceful, loyal.   Weaknesses: dictatorial, inhibited, conceited, distrusting, unimaginative",
		temperament: "Capricorns are very ambitious people, they always have something they are pursuing and they want their lives to be fulfilled and important. Capricorns are extremely patient and will wait a long time for something they want, when the opportunity arises, they will plan their steps carefully to others, they might appear hesitant but this is not true, they know that there is only one chance to succeed and they are filing together their information to take the proper steps to accomplish their goal with flying colors, not just second rate. Capricorns have a very active mind and strong powers of concentration. Capricorns like being in control of their surroundings and everyone in their life. Capricorns are very cautious but this only to survey the situation before leaping in, they will never make a hasty jump in. They accept change but introduce it slowly so they can get used to it and incorporate it into their life. Capricorns tend to see life in black or white, definitive's only. There are no gray areas for these are areas that are not understood and this makes Capricorn feel uncomfortable. They tend to be in control in a romantic relationship that way they are never vulnerable to another person.",
		img: "img/capricor.jpg"
	},
	{
		sign: "gemini",		
		personality: "Strengths: engergetic, clever, imaginative, witty, adaptable.   Weaknesses: superficial, impulsive, restless, devious, indecisive",
		temperament: "Gemini people are many sided, quick both in the mind and physically. They are brimming with energy and vitality, they are clever with words. They are intelligent and very adaptable to every situation and every person. Gemini are curious and always want to know what's going on in the world around them. They are not one to sit back and watch the world go by, they want to be involved. This can sometimes make Gemini nosy, they do not mind their own business! This is because they really enjoy communicating, more so then most other astrology signs, they are the ultimate social butterfly. Gemini can talk and talk, but they have interesting things to say, their talk is not mindless babble. They have interesting opinions and thoughts on things and are not afraid to speak their mind. They are always in the know and are the one to see for the latest juicy gossip. Lacking perseverance, Gemini easily goes off topic to explore another thought or idea. Gemini are superficial, they will form opinions on matter without diving into them and exploring them fully. This can lead them into thinking they know everything, which they usually do but their mind is too busy to be concerned with fine details. Routine and boredom are Gemini's biggest fears. Gemini would rather be naive then know the depressing truth, they do not want anything putting a damper on their freedom or positive energy. ",
		img: "img/gemini.jpg"
	},
	{
		sign: "leo",		
		personality: "Strengths: confident, ambitious, generous, loyal, encouraging.   Weaknesses: pretentious, domineering, melodramadic, stubborn, vain",
		temperament: "Leo is the lion, this well suited symbol represents Leo very well. They possess a kingdom which they protest and cherish. The are high esteemed, honorable and very devoted to themselves in particular! The kingdom could be anything from work to home to a partner, whatever it is, you rule it. Leo is always center stage and full of flair, they enjoy basking in the spotlight. A Leo always makes their presence known. Leo are full of energy that acts like a magnet for other people. Others are attracted to Leo's wit, charm, and what they have to say for they speak of things grand and very interesting. Leo will never settle for second best. They want only the best which can cause lavish excessive spending habits as they enjoy their life of luxury, which is all to easily justified by the grand and magnificent Leo! Public image is very important to Leo, with luxurious possessions and ways of life, this keeps the public image in high standing. They will do whatever it takes to protect their own reputation. Leos are very generous, kind and openhearted people. If a Leo is crossed, they will strike back with force but they are not one to hold a grudge, they easily forgive, forget and move on. Leos are always trying to make things right in the world, they have larger then life emotions and they need to feel like they have accomplished something at the end of the day. They react to situations with action instead of sitting back and thinking about it, they are not impulsive however because they look at the future and consider consequences of their actions.",
		img: "img/leo.jpg"
	},
	{
		sign: "libra",		
		personality: "Strengths: diplomatic, graceful, peaceful, idealistic, hospitable.  Weaknesses: superficial, vain, indecisive, unreliable",
		temperament: "Libras are the diplomat of the zodiac. They are able to put themselves in other's shoes and see things through another person's point of view. They are the ones that always want to make things right and have balance and harmony in their life, their surroundings and the lives of the people close to them. They have captivating charm, elegant taste and they are easy to like due to their eager-to-please, easygoing nature. In return for a Libra's amazing ability to be a good listener, sooth and calm people, they expect admiration. Libras will gather a group of people, everyone will become friends then the Libra will be in the center of the group. They like the attention and the admiration for the people that they have brought together. Libras are very intelligent, they often hide this inside their easygoing exterior. They express their intelligence through creativity, most are involved in some sort of artistic or creative pursuit. Many people overlook just how intelligent a Libra actually is. When others see a Libras wide range of interests and hobbies, their intelligence and creativity is more then obvious. Libras love variety and different situations. They welcome change. Libras love luxury. They will spend lots of money and surround themselves with beautiful things and they seem to be constantly fussing over their appearance. They love anything upscale and classy. Libras work hard to please others, this they do an others find them incredibly captivating.",
		img: "img/libra.jpg"
	},
	{
		sign: "sagittarius",		
		personality: "Strengths: Independence is Sagittarius' principle, they crave adventure and excitement and welcome change with open arms. Sagittarius is the sign of the philosopher and the explorer, they will go as far as road will go and explore every corner thoroughly in their ever eternal search for wisdom. Freedom is so important to Sagittarius that they will actually make decisions based on the amount of freedom that is given by the choice they have made, as a result, sometimes a good opportunity is turned down because of it's high commitment need, but this is their choice so it is a good choice for them.",
		temperament: "Weakness:  unemotional, Sagittarius seem to be guided by luck, good things happen to Sagittarius and this is usually because of their optimistic outlook and positive disposition which attracts good fortune. Despite hardships, Sagittarius is always optimistic that good things will happen tomorrow and the future carries good luck. Sagittarius have a vibrant, expansive personality that is free like a bird, Sagittarius cannot be contained. They are full of curiosity and they always look forward to the future, never dwelling on the past. Sagittarius are detached from emotions because emotions hold a person back, they do not like to talk about their feelings, they simply experience them and move on. Sagittarius can be reckless and irresponsible because they will jump at a suggestion of something new before they weigh the advantages and disadvantages",
		img: "img/sagittarius.jpg"
	},
	{
		sign: "scorpio",		
		personality: "Strengths: loyal, passionate, resourceful, observant, dynamic Weaknesses: Jealous, Obsessive Manipulative",
		temperament: "Scorpio is the astrology sign of extremes and intensity. Scorpios are very deep, intense people, there is always more then meets the eye. They present a cool, detached and unemotional air to the world yet lying underneath is tremendous power, extreme strength, intense passion and a strong will and a persistent drive. Scorpios have a very penetrative mind, do not be surprised if they ask questions, they are trying to delve deeper and figure things out and survey the situation. They always want to know why, where and any other possible detail they can possibly know. Scorpio's are very weary of the games that other people try to play and they are very aware of it. Scorpios tend to dominate and control anyone that lets them, or anyone that they find weak. The person that a Scorpio respects and holds close to them is treated with amazing kindness, loyalty and generosity. On the outside, a Scorpio has great secretiveness and mystery. This magnetically draws people to them. They are known to be controlling and too ambitious but only because they need control for this makes them feel safe. ",
		img: "img/scorpio.jpg"
	},
	{
		sign: "taurus",		
		personality: "Strengths: dependable, persistant, loyal, patient, generous.  Weaknesses: stubborn, laziness, possessive, materialistic, self-indulging",
		temperament: "Taurus is the one who has immense perseverance, even when others have given up, the Taurus rages on. Solid and persistent, just like the bull, which is Taurus' well suited symbol. Taurus's have a well known reputation for being stubborn, which is not necessarily a bad thing. The stubborn streak can cause Taurus to butt heads and conflict with other strong character types. Taurus are not fond of change. They like the familiar and routine comfort of life. Taurus is easy going and not one to pick a fight but should some poor souls attempt to provoke Taurus, the wrath will be known, for they have a temper underneath the calm surface. Taurus are very responsive to their surroundings. They like decorations, color, anything that appeals to all the senses. Taurus like possessions and the Taurus home is nicely decorated with lots of things. Taurus are down to earth, they do not like gaudy, flashy or over the top things. They prefer comfortable and creative settings and objects. Taurus likes security, in every aspect of their lives from home, to love, to career. Taurus can be secretive, opinionated and stingy. Taurus tend to be self-indulgent and lazy, Taurus are master procrastinators of the astrology zodiac! They do however have a strong, persistent drive that comes to life when they chose, and no one would ever know that they are lazy. The secret to this is that their laziness is pushed aside when it comes to themselves. ",
		img: "img/taurus.jpg"
	},
	{
		sign: "virgo",		
		personality: "Strengths: analytical, observant, helpful, reliable, precise.   Weaknesses: skeptical, fussy, inflexible, cold, interfering",
		temperament: "Virgo exists in the mind, everything is inside. To the world, Virgo presents a calm and collected exterior but on the inside, nervous uncontrolled intensity in the mind, trying to figure things out, how to improve everything, analyzing and thinking. Virgo can tire itself out without even moving! Virgo has a constant drive to improve and perfect, this can lead to extreme pickiness and finickiest. They are pure, their motives are honest never malicious and they want to accomplish something. ",
		img: "img/virgo.jpg"
	}	
]
function getInfo(){
	var sign = document.getElementById("sign").value

for(var i = 0; i < zodiac.length; i++){
	if(sign == zodiac[i].sign) {
		document.getElementById("sign").innerHTML = zodiac[i].sign
		document.getElementById("personality").innerHTML = zodiac[i].personality
		document.getElementById("temperament").innerHTML = zodiac[i].temperament
		document.getElementById("img").setAttribute("src", zodiac[i].img)
		return
		
	}
  }
}
document.body.style.backgroundImage = "url('img/zodiac.png')";
document.body.style.backgroundRepeat = "no-repeat";
document.body.style.backgroundPosition = "top right";
